'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InvProducts
    
    '''<summary>
    '''litMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litMessage As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlProductListing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProductListing As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rptrProductListing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptrProductListing As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlProductsUpdateDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProductsUpdateDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewCategory As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ddlBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBrand As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewBrand As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUOM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewUOM As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrice As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtOnHandQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnHandQty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMinOnHandQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinOnHandQty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReorderQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReorderQty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlLssProduced control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlLssProduced As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSaveProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveProduct As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewProduct As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnReturn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnReturn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlProductProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProductProperties As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litNewPropertyImage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litNewPropertyImage As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''rptrProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptrProperties As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlAddMultiplePropertyToProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddMultiplePropertyToProduct As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlPropertiesAdd1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd1 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd2 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails2 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd3 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails3 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd4 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails4 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd5 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails5 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd6 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails6 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd7 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails7 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd8 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails8 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd9 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails9 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlPropertiesAdd10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd10 As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails10 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveAddMultipleProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAddMultipleProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelAddMultipleProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAddMultipleProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlAddPropertyToProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddPropertyToProduct As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlPropertiesAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveAddProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAddProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelAddProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAddProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewCategory As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewCategory As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewBrand As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewBrand As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNewBrand As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewBrand As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewUOM As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewUOM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNewUOM As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewUOM As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewProperty As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewProperty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveNewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNewProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewProperty As Global.System.Web.UI.WebControls.Button
End Class
