'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InvRawMaterials
    
    '''<summary>
    '''pnlRawMaterialListing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRawMaterialListing As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''rptrRawMaterialListing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptrRawMaterialListing As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''pnlRawMaterialUpdateDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRawMaterialUpdateDetails As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCategory As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewCategory As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ddlBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBrand As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewBrand As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescription As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ddlUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUOM As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgNewUOM As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''txtOnHandQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOnHandQty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtMinOnHandQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinOnHandQty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtReorderQty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReorderQty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveNewRawMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNewRawMaterial As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewRawMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewRawMaterial As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlRawMaterialProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRawMaterialProperties As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''litRawMaterialProperties control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents litRawMaterialProperties As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''pnlAddPropertyToRawMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlAddPropertyToRawMaterial As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''ddlPropertiesAdd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPropertiesAdd As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtAddPropertyDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddPropertyDetails As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveAddProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveAddProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelAddProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelAddProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewCategory As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCategory As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddNewCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewCategory As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewBrand As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewBrand As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNewBrand As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewBrand As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewUOM As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewUOM As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNewUOM As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewUOM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewUOM As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''pnlNewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlNewProperty As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''txtNewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNewProperty As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveNewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveNewProperty As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnCancelNewProperty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancelNewProperty As Global.System.Web.UI.WebControls.Button
End Class
